image:
  repository: $CI_REGISTRY_IMAGE
  tag: master

nameOverride: sample-next-app

deployment:
  port: "3000"

  livenessProbe:
    periodSeconds: 20
    port: "3000"
  readinessProbe:
    periodSeconds: 20
    port: "3000"

  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 64Mi

  env:
    - name: PORT
      value: "3000"
    - name: NODE_ENV
      value: "production"
# ingress:
#   enabled: true
#   annotations:
#     appgw.ingress.kubernetes.io/ssl-redirect: "true"
#     kubernetes.io/ingress.class: "azure/application-gateway"
#   hosts:
#     - host: "sample-next-app.fabrique.social.gouv.fr"
#       paths:
#         - path: /
#           servicePort: "80"

#   tls:
#     - hosts:
#         - "sample-next-app.fabrique.social.gouv.fr"
#       secretName: sample-next-app-crt
