#
# Context investigation
#
# - master as prod
# - features branches env
#

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops_simple_app.yml
    ref: migrate
    #ref: 3a5b61a79702cbbf88215e660b2a6062cf50b159
# - project: SocialGouv/gitlab-ci-yml
#   file: /base_azure_db_stage.yml
#   ref: 82c62b1f49ad40beeefda665166c94227803cba5
# - project: SocialGouv/gitlab-ci-yml
#   file: /base_migrate_azure_db.yml
#   ref: v9.1.1

#
# stages:
#   - Deploy

variables:
  PROJECT: "sample-next-app"
  VALUES_FILE: ./.k8s.app.values.yml
  ENABLE_AZURE_POSTGRES: 1
  TEST_DISABLED: 1
  CODE_QUALITY_DISABLED: 1

.base_migrate_azure_db:
  extends:
    - .base_managed_pg
  stage: Deploy
  allow_failure: true
  variables:
    GIT_STRATEGY: none
    #
    HELM_RENDER_ARGS: --set db.name=db_${CI_PIPELINE_ID}
      --set db.password=pass_${CI_PIPELINE_ID}
      --set db.user=user_${CI_PIPELINE_ID}
      --set migrate.image.repository=${CI_REGISTRY_IMAGE}
      --set migrate.image.tag=${CI_COMMIT_SHA}
      --set migrate.command=env
      --set migrate.args[0]=-v
    HELM_APPLY_ARGS: >-
      -l app=migrate

Migrate Azure DB (dev):
  extends:
    - .base_migrate_azure_db
