variables:
  AUTO_DEVOPS_PRODUCTION_AUTO: "/^v/"

Test gitlab rule inline:
  rules:
    - if: "$PRODUCTION"
      when: never
    - if: /^test/ =~ $CI_COMMIT_MESSAGE
      when: on_success
    - if: $CI_COMMIT_REF_NAME
      when: manual

Test gitlab rule inline:
  rules:
    - if: "$PRODUCTION"
      when: never
    - if: /^test/ =~ $CI_COMMIT_MESSAGE
      when: on_success
    - if: $CI_COMMIT_REF_NAME
      when: manual
