#
# Context investigation
#
# - master as prod
# - features branches env
#

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops_simple_app.yml
    ref: v7.1.0

variables:
  PROJECT: "sample-next-app"
  PORT: 4000
  VALUES_FILE: ./.k8s/app.values.yml

Register image Hasura:
  extends: .base_register_stage
  stage: Registration
  variables:
    CONTEXT: ./hasura
    DOCKERFILE_PATH: Dockerfile
    IMAGE_NAME: $CI_REGISTRY_IMAGE/hasura

Deploy app Hasura (dev):
  extends:
    - .deploy_app_stage
  except:
    refs:
      - tags
      - master
  variables:
    HOST: hasura-${CI_ENVIRONMENT_SLUG}-${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}
    VALUES_FILE: ./.k8s/hasura.values.yml
  environment:
    name: review/${CI_COMMIT_REF_NAME}-dev
    url: https://hasura-${CI_ENVIRONMENT_SLUG}-${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}
