#
# Context investigation
#
# - master as prod
# - features branches env
#

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v16.0.0-alpha.8

variables:
  AUTO_DEVOPS_RELEASE_AUTO: "true"
  AUTO_DEVOPS_PRODUCTION_AUTO: "true"

Review:
  extends: .autodevops_review
  rules:
    - if: "$PRODUCTION || $RELEASE || $CI_COMMIT_TAG"
      when: never
    - when: on_success

Preprod:
  extends: .autodevops_preprod
  rules:
    - if: "$PRODUCTION || $RELEASE"
      when: never
    - if: "$CI_COMMIT_TAG"
