#
# Context investigation
#
# - master as prod
# - features branches env
#

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v16.0.0-alpha.9

variables:
  AUTO_DEVOPS_RELEASE_AUTO: "true"
  AUTO_DEVOPS_PRODUCTION_AUTO: "true"
