include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v17.0.0-beta.15

variables:
  AUTO_DEVOPS_RELEASE_AUTO: "true"
  AUTO_DEVOPS_PRODUCTION_AUTO: "/^v1\.1\.0-beta\.[0-9]+$/"

  AUTO_DEVOPS_DEV_ENVIRONMENT_NAME: "-dev2"
  AUTO_DEVOPS_PREPROD_ENVIRONMENT_NAME: "-dev2"
  AUTO_DEVOPS_PROD_ENVIRONMENT_NAME: "prod2"
