variables:
  AUTO_DEVOPS_PRODUCTION_AUTO: "/^v/"

Test gitlab rule inline:
  rules:
    - if: "$PRODUCTION"
      when: never
    - if: /^test/ =~ $CI_COMMIT_MESSAGE
      when: on_success
    - when: manual
    script:
      - echo "${CI_JOB_NAME}"

Test gitlab rule not match inline:
  rules:
    - if: "$PRODUCTION"
      when: never
    - if: /^teust/ =~ $CI_COMMIT_MESSAGE
      when: on_success
    - when: manual
    script:
      - echo "${CI_JOB_NAME}"
review:
  script:
    - DYNAMIC_ENVIRONMENT_URL="$RANDOM.com"
    - echo "DYNAMIC_ENVIRONMENT_URL=$DYNAMIC_ENVIRONMENT_URL" >> deploy.env
  artifacts:
    reports:
      dotenv: deploy.env
  environment:
    name: $CI_COMMIT_REF_SLUG-dev2
    url: $DYNAMIC_ENVIRONMENT_URL

stop_review:
  dependencies: [review]
  stage: deploy
  script:
    - echo "DYNAMIC_ENVIRONMENT_URL=$DYNAMIC_ENVIRONMENT_URL"
