include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v17.0.0-beta.7

variables:
  AUTO_DEVOPS_RELEASE_AUTO: "true"
  AUTO_DEVOPS_PRODUCTION_AUTO: "/^v[1-9]+\\.[0-9]+\\.[0-9]+$/"
