include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v17.0.0-beta.28

variables:
  AUTO_DEVOPS_RELEASE_AUTO: "🔖"
  AUTO_DEVOPS_PRODUCTION_AUTO: "🚀"

Trigger Production:
  extends: .autodevops_trigger_production
  rules:
    - if: "$PRODUCTION"
      when: never
    - if: $AUTO_DEVOPS_PRODUCTION_AUTO =~ $CI_COMMIT_TAG
      when: on_success
    - if: "$CI_COMMIT_TAG"
      when: manual
